language: node_js
node_js:
 - "9"
dist: trusty
sudo: true
addons:
  chrome: stable

before_script:
 - npm install -g @angular/cli

script:
 - node_modules/.bin/karma start --single-run --browsers ChromeHeadless karma.conf.js
